services:
  app:
    image: container-registry.fornaxict.hu:5005/karsai.bence/privateclinic/backend:${CI_BUILD_TAG}
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    volumes:
      #- /home/docker:/var/www/html
      - /var/www/html/storage
      - /var/www/html/bootstrap/cache
      - /home/docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
    env_file: ".env"
    ports:
      - 9000:9000
    depends_on:
      - db
    networks:
      - mysql-phpmyadmin

  db:
    image: mysql:5.7
    environment:
      #MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: privateclinic
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_CHARSET: utf8mb4  
      MYSQL_COLLATION: utf8mb4_hungarian_ci
    volumes:
      - /home/docker/data:/var/lib/mysql
      - /home/docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 3306:3306
    networks:
      - mysql-phpmyadmin
  nginx:
    image: container-registry.fornaxict.hu:5005/karsai.bence/privateclinic/frontend:${CI_BUILD_TAG}
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - mysql-phpmyadmin
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      #MYSQL_ROOT_PASSWORD: 
    ports:
      - "8080:80"
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
    driver: bridge
    enable_ipv6: false
  
volumes:
  db_data:
